app : 
  name : "go-todolist"
  version : "1.0.0"
  author : "Aldi Syah Putra"

web : 
  port : 3000

database : 
  username : "root"
  password : ""
  host : "localhost"
  port : 3306
  name : "todolist"